services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_retail_data
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
